export enum ENVIRONMENT_SUFFIX {
  DEV = '_dev',
  STAGE = '_stage',
  PROD = '_prod',
}

export enum PLATFORM {
  IOS = 'ios',
  ANDROID = 'android',
}

export enum PROVIDERS {
  FACEBOOK = 'facebook',
  GOOGLE = 'google',
  APPLE = 'apple',
}

export enum NOTIFICATION_TYPE {
  NEW_CALL,
  SCHEDULED_CALL_READY,
  SCHEDULED_CALL_ADDED,
  SCHEDULED_CALL_CANCELED,
  CLICK_IN_ADDED,
  CLICK_IN_CANCELLED_FROM_SHOP,
  CLICK_IN_CANCELLED_FROM_CUSTOMER,
  CLICK_IN_EDITED,
  ORDER_PENDING,
  ORDER_DECLINED,
  ORDER_ACCEPTED,
  ORDER_PROCESSING,
  ORDER_SHIPPED,
  ORDER_DELIVERED,
  REFER_A_FRIEND,
  NEW_VOUCHER,
  NEW_CALL_TO_INVITED,
  NEW_SCHEDULED_CALL_TO_INVITED,
  IMAGE_PROCESS_ERROR, // ONLY FOR EMAILS, NOT USED IN APP
  SCHEDULED_CALL_EARLY,
  SCHEDULED_CALL_CANCELED_TO_INVITED,
  MARKETING_GENERAL,
  MARKETING_NEWSLETTER,
  MARKETING_PRODUCT,
  MARKETING_SHOP,
}
